const express = require('express')
const authMiddleware = require("../middlewares/auth.middleware")
const interviewController = require("../controllers/interview.controller")
const interviewRouter = express.Router()
const upload = require("../middlewares/file.middleware");

/**
 * @route POST/api/interview/
 * @description generate new interview report on the basis of user self description,resume pdf and job description
 * @access private
 * 
 */
interviewRouter.post("/",authMiddleware.authUser,upload.single("resume"),interviewController.generateInterViewReportController);


/**
 * @route GET/api/interview/report/:interviewID
 * @description get interview report bi interviewID.
 * @access private
 */
interviewRouter.get("/report/:interviewId",authMiddleware.authUser,interviewController.getInterviewReportByIdController);


/**
 * @route GET/api/interview/
 * @description get all the reports that are generated by the logged in users.
 * @access private
 */
/**
 * @route POST /api/interview/voice-qa
 * @description Ask AI a question about the interview report
 * @access private
 */
interviewRouter.post("/voice-qa", authMiddleware.authUser, interviewController.voiceQAController);
interviewRouter.get("/",authMiddleware.authUser,interviewController.getAllInterviewReportsController);
module.exports = interviewRouter;